apiVersion: v1
kind: Pod
metadata:
  labels:
    name: dind-pod
  annotations:
    "jenkins.io/jnlp-container": "jnlp"
spec:
  containers:
    - name: docker
      image: docker:latest
      securityContext:
        privileged: true
    - name: jnlp
      image: jenkins/inbound-agent:latest
      securityContext:
        runAsUser: 1000
        fsGroup: 1000