# Default values for helm-chart-malmquist-fe.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nmmalmquist/malmquist-fe
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  port: 3000

service:
  type: NodePort
  port: 3000
  nodePort: 31000

livenessProbe:
  httpGet:
    path: /
    port: 3000
readinessProbe:
  httpGet:
    path: /
    port: 3000

#use replica count if autoscaling is disabled
replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80